### ISSUE TITLE
The 999 acknowledgement is kept in memory until parsing is ready

### ISSUE THREAD

**Issue by ineedteepee** [BerryWorksSoftware/edireader#1]
EDIAbstractReader.setAlternateAcknowledgment(Writer) uses a BranchingWriter when writing EDI 999 acks. There is a small inconsistency in the code, since BranchingWriter is documented as "not appropriate for arbitrarily large volumes of data" and the parsed files can be of arbitrary length.

For example, with 29k transactions, the in memory size of the trunk and branch StringWriters total to 2.4MB.

**Comment by canabrook** [comment]
Can you please provide more information on the problem. I am not sure if this is a documentation issue or a design issue. If the acknowledgement generating feature is enabled to generate 997s and 999s, the BranchingWriter is used to write the acknowledgment and does buffer content in memory. Acknowledgements are typically quite limited in size and this does not seem to be a resource problem. It does not impact ability of the core parser to handle arbitrarily large input. If the BranchingWriter class were used independently, it could have memory constrains, but this is not the case in how it is used within EDIReader.
