### ISSUE TITLE
Unknown Syntax Identifier in UNB segment: UNOL

### ISSUE THREAD

**Issue by MathieuLavigneCC** [BerryWorksSoftware/edireader#15]
I try to parse a file starting with this segments :

```
UNA:+,? 'UNB+UNOL:3+
```

I have found that the parser is expecting the "UNO" string to be followed by a character from A to K but I do not understand why ?

**Comment by canabrook** [comment]
The specs I consulted described proper values as UNOA, UNOB, ..., UNOK, and possibly UNOX or UNOY.  That is why the parser does what you are seeing. Are you just curious, or are there some other values that are appropriate? It would be easy enough for me to relax this check, but I would want to understand the scenarios where this was valid or an accepted convention.

**Comment by MathieuLavigneCC** [comment]
Thanks for your answer Canabrook. The UNOL syntax is used by some french administration agency. I've made a fork that adds the case 'L' and it seems to work, but I don't know what it may involve.

**Comment by canabrook** [comment]
I'm sure the change you made will work just fine. I plan to push a new release very soon that relaxes this test, probably to accept any letter in that position. Thanks for the info.

**Comment by canabrook** [comment]
Release 5.4.19 allows UNOL as discussed above.

**Comment by MathieuLavigneCC** [comment]
Glad to here this. Thank you !
