### ISSUE TITLE
Support for transaction 310 and 315 EDI

### ISSUE THREAD

**Issue by sachinboob** [BerryWorksSoftware/edireader#17]
Hello team,

I attempted to parse the transactions 310 and 315 EDI files using edireader library.

However, it failed with message as 

> Invalid beginning of segment at segment 58

Line 58 is EOF.

If I use the sample edi file provided in another project - https://github.com/BerryWorksSoftware/edi-json/blob/master/Sample824.edi

then the program runs fine.

I suspect the support is limited to only the specific versions that are mentioned in the readme file - 270, 271, 276, 277, 278, 834, 835, 837 ?

If this is not the case, and if it is expected that edireader library should be able to parse any EDI file then probably I will add the EDI file here by removing sensitive data and the code that I am using so that the issue can be triaged.

Please let me know.
Thanks.

**Comment by sachinboob** [comment]
@canabrook 

#13 is a similar question to parse a different EDI . May be such an example can help.

**Comment by canabrook** [comment]
The edireader library is expected to parse any valid edi -- and even merely
reasonably valid edi -- so I will certainly want to study this one
carefully and provide a solution. It may be a day or two as I'm traveling.

**Comment by sachinboob** [comment]
@canabrook Thank you for your response. The EDI file that I was using did not have correct ending segments. Hence there was the error, which indeed the correct behavior. Closing this issue now. Will open a separate ticket in case there is any other problem I face.
