### ISSUE TITLE
Missing Loops when parsing a 837 edi

### ISSUE THREAD

**Issue by pknelakuditi** [BerryWorksSoftware/edireader#2]
EdiReader 5.4.3 is not creating loop when converted from edi to xml. I am using EDItoXML.java to convert a sample 837 file to xml which is generating loop structures for version 4.7.3 but not for the latest version. This is issue is caused due to the missing 837 plugin(ANSI_837.java) in 5.4.3 .

**Comment by SethNJohnson** [comment]
Is this still an issue?  Should we use 4.7.3 instead?

**Comment by msimon3** [comment]
Had the same issue. Replacing the missing file fixes it for me.
