### ISSUE TITLE
Edifact missing Sender & Receiver qualifier of UNG segment

### ISSUE THREAD

**Issue by justanu** [BerryWorksSoftware/edireader#7]
So I have this EDIFACT UNG
UNG+INVOIC+LOCK:02+CBP-ACE-TEST:02+041013:1901+16+UN+D:98A:'

Expected:
`<group GroupType="INVOIC" ApplSender="LOCK" ApplSenderQual="02" ApplReceiver="CBP-ACE-TEST" ApplReceiverQual="02" Date="041013" Time="1901"  Control="16"  StandardCode="UN" MessageVersion="D" MessageRelease="98A" Code="">`

Actual:
`<group GroupType="INVOIC" Control="16" StandardCode="UN">`

**Comment by canabrook** [comment]
Can you provide a small interchange with this UNG that illustrates your issue? I put the UNG in a small interchange, and get this XML which I believe is correct. 

<group GroupType="INVOIC" ApplSender="LOCK" ApplReceiver="CBP-ACE-TEST" Date="041013" Time="1901" Control="16" StandardCode="UN" StandardVersion="D98A">

I am very interested in why you are seeing a different result. I do notice that the "02" qualifiers are not provided in the XML I get, but that seems to be unrelated to your issue.

**Comment by canabrook** [comment]
I your main point that the "02" qualifiers are not included in the XML for the UNG group? Or that you are getting the GroupType, Control, and StandardCode attributes?  I can easily provide the qualifiers if that is an issue, but if you getting what you show as the actual result, then that is a different issue.

**Comment by justanu** [comment]
Will provide test case with data later today.

I might be using an older version 5.4.1 that has the bug.

**Comment by canabrook** [comment]
Great. I am working on adding the "02" qualifiers to the XML for the UNG. That will not be difficult. The UNG/UNE structures seem to be rarely used, so it will be good to have you confirm the change when I am finished.

**Comment by justanu** [comment]
On Dec 21, 2017 6:28 AM, "Scott Mayberry" <notifications@github.com> wrote:

I your main point that the "02" qualifiers are not included in the XML for
the UNG group? Or that you are getting the GroupType, Control, and
StandardCode attributes? I can easily provide the qualifiers if that is an
issue, but if you getting what you show as the actual result, then that is
a different issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BerryWorksSoftware/edireader/issues/7#issuecomment-353328247>
,

**Comment by justanu** [comment]
Sorry I might have sent uodates in error, please disregard.

As I mentioned, I will provide test cases today.

**Comment by justanu** [comment]
Here is the Edifact source:

`UNB+UNOA:2+YOUR_GLN_LOCATIONNUMBER:14+7080000368921:14+070323:0839+20070323083902++++++0'
UNG+INVOIC+LOCK:02+CBP-ACE-TEST:02+041013:1901+16+UN+D:98A:'
UNH+403+INVOIC:D:98A:UN:TBF10'
BGM+380+3430296768'
DTM+137:20070322:102'
FTX+INV+1++Free text to be handled manually'
RFF+ON:1001234'
NAD+SU+YOUR_GLN_LOCATIONNUMBER::9++Acme+ADDRESS 1+ADDRESS 2++ZIPCode+SE'
RFF+VA:SE123456789012'
NAD+BY+7080005037129::9++JÄRNBODEN I SALA AB+BOX 105+SALA++733 22+SE'
NAD+IV+7080001070175::9++JERNIA AS+FLÖISBONNVEIEN 4+KOLBOTN++1411+NO'
NAD+DP+7080005037129::9++JÄRNBODEN I SALA AB+FABRIKSGATAN 4+SALA++733 39+SE'
CUX+2:SEK:4'
PAT+3'
DTM+13:20070530:102'
ALC+C++++FC:::FREIGHT'
MOA+8:50'
LIN+1++1234567890123:EN'
PIA+1+12345678:SA'
IMD+F++:::ITEM DESCRIPTION IN CLEAR TEXT'
QTY+47:2:STK'
MOA+203:179.2'
PRI+AAB:128::::STK'
PRI+AAA:89.6::::STK'
RFF+ON:1001234:10'
TAX+7+VAT+++:::25.0+S'
ALC+A++++OTE:::Discount'
PCD+3:30:13'
MOA+8:76.8'
UNS+S'
CNT+2:1'
MOA+150:57.3'
MOA+86:286.5'
MOA+203:179.2'
MOA+125:229.2'
MOA+259:50'
TAX+7+VAT+++:::25.0+S'
MOA+176:57.3'
UNT+37+403'
UNE+1+16'
UNZ+1+20070323083902'`

**Comment by justanu** [comment]
Scott,
I also noticed few performance improvements I would suggest to do on the EDIReader. Do you mind if I make few suggestions (in a separate ticket)?

**Comment by canabrook** [comment]
Thanks for the EDIFACT sample. Do you mind if it becomes part of a regression suite? I'm assuming it contains nothing sensitive.  Notice that I did a small code push an hour or so ago to handle the qualifiers in the UNG segment. 

I would be glad to hear your performance improvement suggestions. We can take that offline using personal email as far as I'm concerned, if that is OK with you. You can email me at info@berryworkssoftware.net.

**Comment by justanu** [comment]
Sure, no problem about the EDIFACT sample (I got it off the net as well). Would you be able to build the code and issue a new release and tag it so I can get the jar file add it to my project?

Will send shortly my email and take offline the discussion,

**Comment by canabrook** [comment]
Here is the XML produced for your sample. I think this is what you are wanting to see. I’ll do the tagged release with pre-built jar file for you. I probably ought to consider releasing it to Maven Central also so that a simple Maven dependency is all you need, but that may take a bit of time.

Scott

**Comment by justanu** [comment]
Thanks. Will be great if you could tag and release to both GitHub and Maven central. Right now the versions are out of sync and documentation is sometimes confusing regarding the latest version.
Let me know if I can help somehow. 

Will test and close ticket if tests passed.

**Comment by justanu** [comment]
Good job, V5.4.12 fixed the issue. Here is the result:

`UNG+INVOIC+LOCK:02+CBP-ACE-TEST:02+041013:1901+16+UN+D:98A:'`

`<group GroupType="INVOIC" ApplSender="LOCK" ApplSenderQual="02" ApplReceiver="CBP-ACE-TEST" ApplReceiverQual="02" Date="041013" Time="1901" Control="16" StandardCode="UN" StandardVersion="D98A">
`
