### ISSUE TITLE
EDIReader Community Edition in Maven Central repository

### ISSUE THREAD

**Issue by eyadsibai** [BerryWorksSoftware/edireader#9]
the EDIReader Community Edition is not available through the Maven Central repository.

I was wondering is there a plan to do so? and if not? Is there an example how we can add it from github?

**Comment by canabrook** [comment]
Thanks for the suggestion. I did get a release into Maven Central repository some time back, but have not added later releases. I will look into re-engaging with Maven Central.

**Comment by bangert** [comment]
I too think this would be fantastic!

**Comment by artisancreek** [comment]
Any update on getting an updated version up to Maven Central Repository?

**Comment by breucode** [comment]
@canabrook Would it be ok for you if I provided a PR to host the artifact on GitHub packages? I would then also suggest (and implement) to switch to github actions from gitlab ci since it should be far easier and less complex to build and publish.

**Comment by mohanrao** [comment]
@canabrook any update on this?
